Deal with file changes better:
* Exit if there are changes in the working directory already
* Do not checkout if the branch is already checked out (only really
  relevant for the first parameter)
* Undo any changes made by the checkout process (but save a patch first!)

diff --git a/git-lazyrebase b/git-lazyrebase
--- a/git-lazyrebase
+++ b/git-lazyrebase
@@ -2,17 +2,27 @@
 
 # upstream=${2:-upstream/develop}
 set -e
+git diff --exit-code || ( echo "Can't rebase with differences" && exit 1 )
 remote=${1:-upstream}
 refspec=${2:-develop}
 shift 2
 for b in "${@}"
 do
+  diff="diff.${b}"
   echo -e "\n\n${b}\n\n"
-  git checkout "${b}" && \
+  ( [ "$(git rev-parse --abbrev-ref HEAD)" = "${b}" ] || \
+      git checkout "${b}" ) && \
+    git diff | tee "${diff}" && \
+    # Undo any changes that may have been done by the checkout
+    git reset --hard && \
     git pull && \
-      # git rebase "${upstream}"
-      git pull "${remote}" "${refspec}" && \
-      	echo -e "\nPushing ${b}" && \
-        	git signpush || \
-          		exit 1
+    # git rebase "${upstream}"
+    git pull "${remote}" "${refspec}" && \
+    echo -e "\nPushing ${b}" && \
+    git signpush || \
+      exit 1
+    if [ -e "${diff}" ]
+    then
+      rm -fv "${diff}"
+    fi
 done
