Don't automatically create a new remote branch if one already exists
- Should resolve an issue where updating a branch on non-default remote
  A fails, so it pushes to the default remote B, creating a redundant
  new branch.

diff --git a/git-signpush b/git-signpush
--- a/git-signpush
+++ b/git-signpush
@@ -25,8 +25,9 @@ git diff --quiet --staged &&
   ( git verify-commit HEAD || git commit --amend --no-edit -S ) &&
     ( git push --force-with-lease "${@}" ||
       git push "${@}" ||
-      ( [[ "${remote}" != "" && "${push}" == "" ]] &&
-      echo "Not pushing: ${branch:-???} from ${remote:-???} to ${push:-???}" ) ||
+      ( [[ "${remote}" != "" || "${push}" != "" ]] &&
+      echo "Abort: ${branch:-???} from ${remote:-???} to ${push:-???}" ) &&
+      exit 1 ||
       git push "${@}" --set-upstream "${defaultRemote}" "${branch}" ) &&
     ( [[ -z "${ci}" ]] && exit 0 ||
       git push --force-with-lease ci
