Simplify for compatibility with MacOS shells (#3)
* Update hook for conan export, rewrite git-pending for current dir
* Only show the first parent with short log aliases:
* Logdiff will hide merged commits using --first-parent
* Check that GPG passphrase is available before committing with
  commit.gpgsign enabled - otherwise, if it fails, the message will be
  lost
* Show log of commit that formatting is being checked against
* Enable building xrpld and tests (which are a subset of xrpld)
* Fix a bug which prevented pre-commit formatting almost all the time
* git remoteadd --upstream option to auto-create "safe" upstream remotes
* Abort if conan does not make a toolchain file
* Parse out project name, and add project-specific settings
* Improve the `squash` command so that the base can be on any remote
* Preserve local merges when pulling
* Follow symlinks in git-pending
* Add / steal some short aliases

diff --git a/git-pending b/git-pending
--- a/git-pending
+++ b/git-pending
@@ -3,14 +3,15 @@
 # Searching for .git without checking type handles git worktrees.
 # TODO: Make the ignore list a param, but for now this works.
 
-if [[ $1 == "-v" ]]
-then
-  verbose=1
-  shift
-fi
+# echo Start
 
-if [[ $1 == "--remote" ]]
+if [[ $1 == "--diff" ]]
 then
+  # This sub-process will exit with non-0 if there are any interesting
+  # differences, a bit like "git diff"
+  #
+  # set -x
+  # pwd
   shift
   [[ $# == 1 ]] || exit 1
   tmp=$1
@@ -27,28 +28,102 @@ then
   # If there are no problems, succeeds, so continue.
   # If there are problems, fails, so exit with a failure.
   git diff --check >& /dev/null || exit 1
+  # There are no interesting differences, exit with success
   exit 0
+fi
+
+if [[ $1 == "--git" ]]
+then
+  git rev-parse --git-dir >/dev/null 2>&1
+  exit $?
+fi
+
+if [[ $1 == "--worktree" ]]
+then
+  # This sub-process will exit with non-0 if this is a valid git work
+  # tree. Additionally, if it is a bare git folder, will output `git
+  # worktree list`.
+  #
+  # set -x
+  # pwd
+  shift
+  [[ $# == 1 ]] || exit 1
+  tmp=$1
+  shift
+  # If in a valid git dir, succeeds, so continue
+  # If in an invalid git dir, fails, so exit with 0
+  git rev-parse --is-bare-repository >& "${tmp}" || exit 0
+  if [[ $( cat "${tmp}" ) == "true" ]]
+  then
+    # This is a bare repo. Show any interesting working trees
+    echo
+    git worktree list | grep -v "(bare)"
+    exit 0
+  fi
+  # This is a valid work tree, so exit with non-0
+  exit 1
+fi
+
+if [[ $1 == "--progress" ]]
+then
+  # This sub-process will output whether any "unusual" operations are in
+  # progress. Exit code only indicates errors
+  # pwd
+  shift
+  [[ $# == 0 ]] || exit 1
+  git status | grep -e "in progress" -e "You have" -e "you are" | head -1
+  exit 0
+fi
+
+# set -x
+
+if [[ $1 == "-v" ]]
+then
+  verbose=1
+  shift
 fi
 
 tmp=$(mktemp)
 
-find $1 \
+search=( "$@" )
+conditions=()
+depth=()
+interesting=( -execdir $0 --diff "${tmp}" \; -o )
+print=( -printf "%h\n" )
+status=( -execdir git status -s -b \; )
+if [[ $1 == "--current" ]]
+then
+  search=( "." )
+  conditions=( -o -execdir $0 --git \; )
+  depth=( -maxdepth 1 )
+  # Default interesting suppresses output if this is in a valid work dir
+  interesting=( -execdir $0 --worktree "${tmp}" \; -o )
+  print=( -printf "\n" )
+  status=( -execdir $0 --progress \; )
+  status+=( -execdir git status -s -b --untracked-files=no \; )
+  shift
+fi
+
+find -L "${search[@]}" \
+  "${depth[@]}" \
   -iname .nih_c -prune -o \
   -iname nih_c -prune -o \
   -iname _deps -prune -o \
-  -iname .git \
-  -execdir git rev-parse \; \
+  \( -iname .git "${conditions[@]}" \) \
+  -prune \
   \( \
-    -execdir $0 --remote "${tmp}" \; \
-    -o \
-    -printf "%h\n" \
-    -execdir git status -s -b \; \
+    "${interesting[@]}" \
+    "${print[@]}" \
+    "${status[@]}" \
     -execdir git diff --check \; \
-    -exec echo \; \
-  \)
+    -printf "\n" \
+  \) \
+  # || echo -e "\n\nTmp:" && cat "${tmp}"
 
 rm -f "${tmp}"
-if [[ -v verbose ]]
+if [[ -n "${verbose}" ]]
 then
   echo Done
 fi
+
+# echo End
diff --git a/git-remoteadd b/git-remoteadd
--- a/git-remoteadd
+++ b/git-remoteadd
@@ -1,8 +1,77 @@
 #!/bin/bash
 
+_run()
+{
+  echo "${@}"
+  "${@}"
+}
+
+if [[ "$1" == "--upstream" && $# -eq 2 ]]
+then
+  # Special case: Create upstream remotes based on origin
+  shift
+  user="$1"
+  # Get the origin URL. Expect it be an SSH-style URL
+  origin=$( git remote get-url origin )
+  if [[ "${origin}" == "" ]]
+  then
+    echo Invalid origin remote >&2
+    exit 1
+  fi
+  # echo "Origin: ${origin}"
+  # Parse the origin
+  ifs_orig="${IFS}"
+  IFS=':' read remote originpath <<< "${origin}"
+  # echo "Remote: ${remote}, Originpath: ${originpath}"
+  IFS='@' read sshuser server <<< "${remote}"
+  # echo "SSHUser: ${sshuser}, Server: ${server}"
+  IFS='/' read originuser repo <<< "${originpath}"
+  # echo "Originuser: ${originuser}, Repo: ${repo}"
+  if [[ "${sshuser}" == "" || "${server}" == "" || "${originuser}" == ""
+    || "${repo}" == "" ]]
+  then
+    echo "Can't parse origin URL: ${origin}" >&2
+    exit 1
+  fi
+  upstream="https://${server}/${user}/${repo}"
+  upstreampush="${remote}:${user}/${repo}"
+  current=$( git remote get-url upstream 2>/dev/null )
+  currentpush=$( git remote get-url upstream-push 2>/dev/null )
+  if [[ "${current}" == "${upstream}" ]]
+  then
+    echo "Upstream already set up correctly. Skip"
+  elif [[ -n "${current}" && "${current}" != "${upstream}" &&
+    "${current}" != "${upstreampush}" ]]
+  then
+    echo "Upstream already set up as: ${current}. Skip"
+  else
+    if [[ "${current}" == "${upstreampush}" ]]
+    then
+      echo "Upstream set to dangerous push URL. Update."
+      _run git remote rename upstream upstream-push || \
+      _run git remote remove upstream
+      currentpush=$( git remote get-url upstream-push 2>/dev/null )
+    fi
+    _run git remote add upstream "${upstream}"
+  fi
+
+  if [[ "${currentpush}" == "${upstreampush}" ]]
+  then
+    echo "Upstream-push already set up correctly. Skip"
+  elif [[ -n "${currentpush}" && "${currentpush}" != "${upstreampush}" ]]
+  then
+    echo "Upstream-push already set up as: ${currentpush}. Skip"
+  else
+    _run git remote add upstream-push "${upstreampush}"
+  fi
+  _run git fetch --jobs=$(nproc) --multiple upstream upstream-push
+
+  exit 0
+fi
+
 if [[ $# -le 1 ]]
 then
-  echo Usage: $( basename $0 ) project user [...]
+  echo "Usage: $( basename $0 ) ( --upstream user | project user [...] )"
   exit 1
 fi
 
diff --git a/githooks-pre-commit b/githooks-pre-commit
--- a/githooks-pre-commit
+++ b/githooks-pre-commit
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [[ -f .clang-format ]] && type -t git-clang-format >& /dev/null \
-  && [[ ! -f "diff.$(git rev-parse --abbrev-ref HEAD)" ]]
+  && [[ ! -f "diff.$(git rev-parse --abbrev-ref HEAD | sed 's/\//./g')" ]]
 then
   g=$( git rev-parse --absolute-git-dir )
   b=$( git rev-parse --abbrev-ref HEAD )
@@ -11,28 +11,51 @@ then
   then
     stash=true
     git stash push --keep-index --quiet
+  fi
 
-    # Format the files
-    git-clang-format --extensions c,cpp,h,cxx,ipp
+  # Format the files
+  git-clang-format --extensions c,cpp,h,cxx,ipp
 
-    # Only uncomment the following line if you want to aggressively ensure
-    # that all formatting across the project is correct, and your version
-    # of `clang-format` doesn't have any incompatibilities.
-    # find src/ripple src/test -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 | xargs -0 clang-format -i
+  # Only uncomment the following line if you want to aggressively ensure
+  # that all formatting across the project is correct, and your version
+  # of `clang-format` doesn't have any incompatibilities.
+  # find src/ripple src/test -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 | xargs -0 clang-format -i
 
-    # Abort the commit if the format is bad.
-    # Pass `--no-verify` to `git commit` to skip this check.
-    # Comment the following line if you want to let the commit complete even if
-    # there are formatting problems.
-    git diff --exit-code
-    code=$?
-    # If we're not in the middle of a merge, restore any unstaged changes
-    # that were stashed.
-    if [[ ! -f ${g}/MERGE_HEAD && "${stash}" == "true" ]]
-    then
-      git restore --quiet -- .
-      git stash pop --quiet
-    fi
+  # Abort the commit if the format is bad.
+  # Pass `--no-verify` to `git commit` to skip this check.
+  # Comment the following line if you want to let the commit complete even if
+  # there are formatting problems.
+  git diff --exit-code
+  code=$?
+  # If we're not in the middle of a merge, restore any unstaged changes
+  # that were stashed.
+  if [[ ! -f ${g}/MERGE_HEAD && "${stash}" == "true" ]]
+  then
+    git restore --quiet -- .
+    git stash pop --quiet
+  fi
+  if [[ $code -ne 0 ]]
+  then
     exit $code
   fi
+fi
+
+
+if [[ "$( git config commit.gpgsign )" == "true" ]]
+then
+  keys=( $( git config --get-all user.signingkey ) )
+  for k in "${keys[@]}"
+  do
+    echo "Checking that passphrase for ${k} can be accessed."
+    echo | gpg --pinentry-mode loopback -o /dev/null --sign --armor \
+      --local-user "${k}" -
+    code=$?
+    if [[ "$code" -ne 0 ]]
+    then
+      echo "Unable to sign using key ${k}."
+      echo "Fix that before writing a commit message that will get lost."
+      echo "e.g. echo | gpg --sign --armor --local-user ${k}"
+      exit $code
+    fi
+  done
 fi
