Several changes
* Logdiff will hide merged commits using --first-parent
* Check that GPG passphrase is available before committing with
  commit.gpgsign enabled - otherwise, if it fails, the message will be
  lost
* Show log of commit that formatting is being checked against

diff --git a/githooks-pre-commit b/githooks-pre-commit
--- a/githooks-pre-commit
+++ b/githooks-pre-commit
@@ -33,6 +33,29 @@ then
       git restore --quiet -- .
       git stash pop --quiet
     fi
-    exit $code
+    if [[ $code -ne 0 ]]
+    then
+      exit $code
+    fi
   fi
+fi
+
+
+if [[ "$( git config commit.gpgsign )" == "true" ]]
+then
+  keys=( $( git config --get-all user.signingkey ) )
+  for k in "${keys[@]}"
+  do
+    echo "Checking that passphrase for ${k} can be accessed."
+    echo | gpg --pinentry-mode loopback -o /dev/null --sign --armor \
+      --local-user "${k}" -
+    code=$?
+    if [[ "$code" -ne 0 ]]
+    then
+      echo "Unable to sign using key ${k}."
+      echo "Fix that before writing a commit message that will get lost."
+      echo "e.g. echo | gpg --sign --armor --local-user ${k}"
+      exit $code
+    fi
+  done
 fi
